"""sync fk constraints

Revision ID: 8db9bd375ac6
Revises: df937d4d3ee7
Create Date: 2026-04-04 09:17:36.191585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db9bd375ac6'
down_revision: Union[str, Sequence[str], None] = 'df937d4d3ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'class_chapters', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_teachers', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quizzes', 'class_chapters', ['class_chapter_id'], ['class_chapter_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'class_teachers', type_='foreignkey')
    op.drop_constraint(None, 'class_chapters', type_='foreignkey')
    # ### end Alembic commands ###
