"""add presentations table

Revision ID: df937d4d3ee7
Revises:
Create Date: 2026-03-30 21:22:16.666077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df937d4d3ee7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        "presentations",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("class_chapter_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("presenton_id", sa.String(), nullable=True),
        sa.Column("presenton_edit_url", sa.Text(), nullable=True),
        sa.Column("cloudinary_url", sa.Text(), nullable=True),
        sa.Column("cloudinary_public_id", sa.Text(), nullable=True),
        sa.Column("template", sa.String(), nullable=True),
        sa.Column("theme", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_chapter_id"],
            ["class_chapters.class_chapter_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.user_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.school_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("presentation_id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quizzes", type_="foreignkey")
    op.drop_constraint(None, "enrollments", type_="foreignkey")
    op.drop_constraint(None, "class_teachers", type_="foreignkey")
    op.drop_constraint(None, "class_chapters", type_="foreignkey")
    op.drop_table("presentations")
    # ### end Alembic commands ###
